### ISSUE TITLE
Fix mobile rendering of ranking page

### ISSUE THREAD

**Issue by MasterIceZ** [gean-dev/pre-toi19#2]
![image](https://user-images.githubusercontent.com/64594596/236817035-11af862d-6ed9-460d-a47b-cf486f2f353e.png)

**Comment by MasterIceZ** [comment]
Plase see: https://tailwindcss.com/docs/responsive-design

**Comment by Thunyatorn** [comment]
Why rendering in mobile เกียน ❓ หรือ ไม่

**Comment by MasterIceZ** [comment]
Fixed https://github.com/gean-dev/pre-toi19/pull/3
